export type PlatformSkillSeed = {
  slug: string;
  name: string;
  description: string;
  category: string;
  bodyMarkdown: string;
  metadataJson?: Record<string, unknown>;
  resources?: Array<{
    resourcePath: string;
    resourceType?: 'reference' | 'template';
    contentMarkdown: string;
  }>;
};

const DOCX_PHASE_SKILLS = [
  'docx_task_router',
  'docx_research_curator',
  'docx_outline_architect',
  'docx_style_system_designer',
  'docx_builder',
  'docx_qa_reviewer',
] as const;

const XLSX_PHASE_SKILLS = [
  'xlsx_task_router',
  'xlsx_source_curator',
  'xlsx_workbook_designer',
  'xlsx_formula_planner',
  'xlsx_builder',
  'xlsx_qa_reviewer',
] as const;

const VERCEL_MCP_PROJECT_CONFIG_TOOLS = [
  'vercel_create_project',
  'vercel_create_project_from_git',
  'vercel_update_project',
  'vercel_update_project_git_repository',
  'vercel_get_project_git_repository',
  'vercel_delete_project',
] as const;

const VERCEL_MCP_RELEASE_SAFETY_TOOLS = [
  'vercel_create_deployment',
  'vercel_get_deployment_events',
  'vercel_add_project_domain',
  'vercel_upsert_env_var',
  'vercel_remove_env_var',
  'vercel_redeploy_deployment',
] as const;

function formatCodeList(values: readonly string[]) {
  return values.map((value) => `\`${value}\``).join(', ');
}

export const PLATFORM_SKILL_SEEDS: PlatformSkillSeed[] = [
  {
    slug: 'requirements-breakdown',
    name: '需求拆解',
    description: '把目标整理成范围、约束和交付项',
    category: 'general',
    bodyMarkdown: [
      '# Skill Brief: 需求拆解',
      '',
      '请先完成以下分析：',
      '- 明确用户目标和核心场景。',
      '- 列出功能范围、非目标和关键约束。',
      '- 输出可执行的交付清单与优先级。',
    ].join('\n'),
  },
  {
    slug: 'implementation-plan',
    name: '实现方案',
    description: '整理技术栈、模块划分和实施顺序',
    category: 'general',
    bodyMarkdown: [
      '# Skill Brief: 实现方案',
      '',
      '请基于当前需求给出实现方案：',
      '- 推荐合适的技术栈和数据存储。',
      '- 拆分核心模块、接口和边界。',
      '- 给出从 MVP 到完善版本的实施步骤。',
    ].join('\n'),
  },
  {
    slug: 'test-checklist',
    name: '测试清单',
    description: '补齐关键测试点和验收标准',
    category: 'general',
    bodyMarkdown: [
      '# Skill Brief: 测试清单',
      '',
      '请围绕当前任务补充测试视角：',
      '- 核心功能用例。',
      '- 边界条件与异常处理。',
      '- 最小验收标准与回归范围。',
    ].join('\n'),
  },
  {
    slug: 'deployment-orchestrator',
    name: '部署编排',
    description: '在部署、重部署、回滚和状态查询时，按项目形态选择正确的修复、发布与验证顺序',
    category: 'deployment',
    metadataJson: {
      systemRole: 'deployment_orchestrator',
      adminManaged: true,
      required: false,
      autoActivation: {
        enabled: true,
        triggers: ['deployment', 'deployable_web_app', 'deploy', 'redeploy', 'rollback', 'status'],
        toolNames: [
          'deploy_application',
          'redeploy_application',
          'rollback_application_deployment',
          'get_application_deployment_status',
        ],
      },
    },
    bodyMarkdown: [
      '# Skill Brief: 部署编排',
      '',
      '请在当前任务涉及部署、重部署、回滚或部署状态查询时，按以下规则执行：',
      '',
      '## 总原则',
      '- 部署相关请求优先使用 OneCEO managed deployment tools，不要只给用户纯文本建议。',
      '- 先识别项目运行时和入口形态，再决定修复路径。',
      '- 区分两类问题：模板/配置问题 与 平台资源绑定问题。',
      '',
      '## 工具选择',
      '- 首次发布或发布当前工作区，用 `deploy_application`。',
      '- 代码更新后的再次发布，用 `redeploy_application`。',
      '- 用户明确要求回滚时，用 `rollback_application_deployment`。',
      '- 用户询问部署进度、URL、健康状态时，用 `get_application_deployment_status`。',
      '',
      '## repair_required 处理',
      '- 若 `repair.category=template_compliance`、`deployment_configuration` 或 `workspace_missing`，允许回到 workspace 修复文件后再重试部署。',
      '- 若 `repair.category=deployment_failed`，根据部署状态、日志和公网访问结果修复启动命令、端口、健康检查或入口文件后再重试部署。',
      '- 若 `repair.category=resource_binding`，不要继续改本地模板；应优先继续修复平台资源绑定，再重试部署。',
      '- 不要把本地 `debug_open_page` 成功误判为线上发布成功。',
      '',
      '## 运行时识别',
      '- HTML / 静态 JS：重点检查 `index.html`、`public/index.html`、静态资源目录、manifest、健康检查入口。',
      '- Node.js / JavaScript：重点检查 `package.json`、build/start 脚本、server 入口、manifest、健康检查。',
      '- Node.js / Express + EJS：若使用 EJS，不要写 `layout(...)` 或依赖 `<%- body %>` 的布局模板，除非项目已安装并接入 `express-ejs-layouts` / `ejs-mate`；否则应改为普通 partial includes。',
      '- Python：重点检查 `requirements.txt` 或 `pyproject.toml`、入口脚本（含 `run.py` / 包式 Flask 入口）、manifest、健康检查。',
      '- Java：重点检查 `pom.xml` / `build.gradle*` / `gradlew`、jar/war 启动方式、manifest、健康检查。',
      '- PHP：重点检查 `index.php` / `public/index.php`、composer、启动根目录、manifest、健康检查。',
      '',
      '## 发布前检查',
      '- 必须确认 build 入口、start 入口、`oneceo.manifest.json`、healthcheck、analytics 注入入口五项都能闭环。',
      '- 如果需要特定运行时细节，按需加载对应 references。',
      '',
      '## 发布完成验证',
      '- 先看 deployment tool 是否 success。',
      '- 再看 deployment status / URL / deploymentId。',
      '- 若仍失败，基于最新 repair category 决定下一步，不要重复做同一类无效修复。',
    ].join('\n'),
    resources: [
      {
        resourcePath: 'references/runtime-classifier.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Runtime Classifier',
          '',
          '- `index.html` / `public/index.html` 为主入口时，优先按静态 HTML / JS 项目处理。',
          '- `package.json` + `server.js|index.js|app.js` 时，优先按 Node.js 项目处理。',
          '- `requirements.txt|pyproject.toml` + `main.py|app.py|server.py|run.py|app/__init__.py` 时，优先按 Python 项目处理。',
          '- `pom.xml|build.gradle|build.gradle.kts|gradlew|mvnw` 时，优先按 Java 项目处理。',
          '- `index.php|public/index.php|composer.json` 时，优先按 PHP 项目处理。',
        ].join('\n'),
      },
      {
        resourcePath: 'references/static-html-js.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Static HTML / JS Deployment Notes',
          '',
          '- 静态项目至少要有 HTML 入口、manifest、可启动的 server 边界和健康检查。',
          '- 若是纯静态资源项目，可补一个简单 Node HTTP server 作为统一运行时边界。',
          '- analytics 注入入口需和平台模板检查使用同一 HTML 入口集合。',
        ].join('\n'),
      },
      {
        resourcePath: 'references/nodejs.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Node.js Deployment Notes',
          '',
          '- 核查 `package.json` 的 `build` / `start`。',
          '- 优先使用明确 server 入口，不要让 start 命令依赖交互式开发服务器。',
          '- 健康检查优先 `/api/system/health`，否则至少保证 manifest 与源码一致。',
        ].join('\n'),
      },
      {
        resourcePath: 'references/python.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Python Deployment Notes',
          '',
          '- 根据框架判定启动方式：FastAPI 常见为 `uvicorn module:app`，Flask 常见为 `gunicorn module:app` 或 `python app.py`。',
          '- 如果项目没有 manifest，需要补齐 build/start/healthcheck 契约。',
        ].join('\n'),
      },
      {
        resourcePath: 'references/java.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Java Deployment Notes',
          '',
          '- 检查 `pom.xml` / `build.gradle*` / wrapper 文件，再决定 build 命令。',
          '- start 命令要明确到可执行 jar/war 或 framework 的正式启动方式，不能只写开发命令。',
          '- 健康检查路径必须与应用真实暴露的 HTTP 路由一致。',
        ].join('\n'),
      },
      {
        resourcePath: 'references/php.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# PHP Deployment Notes',
          '',
          '- 区分入口在根目录还是 `public/` 目录。',
          '- 若是传统 PHP 项目，启动时需要明确 document root。',
          '- `composer.json` 存在时，应同时检查依赖安装策略和运行入口。',
          '- 如果使用 `php -S` 且没有显式健康接口，应把 manifest 的 `healthcheck.path` 设为 `/`，不要默认写 `/api/system/health`。',
        ].join('\n'),
      },
      {
        resourcePath: 'references/deploy-repair-loop.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Deploy Repair Loop Guard',
          '',
          '- 同一 repair category 和同一失败指纹反复出现时，先确认平台检查条件是否真的发生变化。',
          '- 不要在 `resource_binding` 错误下重复改 HTML、manifest 或启动脚本。',
          '- 每次重试前都应说明当前是在修模板、修配置，还是修平台资源绑定。',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'vercel-mcp-project-config-operator',
    name: 'Vercel MCP Project Config',
    description:
      'Keeps Vercel MCP project create/update/delete calls focused on project configuration, not source deployment.',
    category: 'deployment',
    metadataJson: {
      systemRole: 'vercel_mcp_project_operator',
      adminManaged: true,
      required: false,
      autoActivation: {
        enabled: true,
        triggers: ['vercel', 'project-config'],
        toolNames: [...VERCEL_MCP_PROJECT_CONFIG_TOOLS],
      },
    },
    bodyMarkdown: [
      '# Skill Brief: Vercel MCP Project Config',
      '',
      'Use this only when a Vercel MCP project configuration tool is being called.',
      '',
      '## Applies To',
      `- ${formatCodeList(VERCEL_MCP_PROJECT_CONFIG_TOOLS)}`,
      '',
      '## Required Checks',
      '- Confirm the Vercel auth context, team, and target project before writing configuration.',
      '- For Git binding tools, confirm the team, project, and repo before writing repository linkage.',
      '- Inspect the workspace files and package scripts before changing framework, buildCommand, installCommand, outputDirectory, or rootDirectory.',
      '- Treat delete as destructive: only proceed when the user explicitly asked to delete the project and the tool confirmation fields are satisfied.',
      '',
      '## Hard Boundaries',
      '- `vercel_update_project` changes project settings only. It does not upload the current workspace or create a new deployment.',
      '- Git repository binding tools manage the project-to-repository relationship only; they do not upload source code.',
      '- Do not change rootDirectory, framework, or outputDirectory to fix deployment failures unless repository evidence supports that specific change.',
      '- Do not invent zip, tar, curl, or raw REST upload flows when the available MCP tools do not expose source deployment.',
      '- If the user asks for first-time source deployment and no deployment-upload tool exists, say the current Vercel MCP can configure projects but cannot upload this workspace.',
      '- For Vercel CLI source deployment, the official path is `vercel deploy`; for prebuilt output it is `vercel build` followed by `vercel deploy --prebuilt`.',
      '',
      '## Configuration Guardrails',
      '- Vercel auto-detects frameworks, so only override `framework` when the repository evidence is clear.',
      '- Vite and many static builds commonly output `dist`; Next.js should not be forced to `dist` unless the project is explicitly static export.',
      '- Never mark local build success as a completed Vercel deployment unless a Vercel deployment tool returned a deployment id or URL.',
    ].join('\n'),
    resources: [
      {
        resourcePath: 'references/vercel-project-config.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Vercel Project Config Notes',
          '',
          '- Official docs: https://vercel.com/docs/project-configuration',
          '- Project config overrides defaults such as `framework`, `buildCommand`, `installCommand`, and `outputDirectory`.',
          '- Build and deploy docs: https://vercel.com/docs/cli/deploy',
          '- Prebuilt CLI deployments use `vercel build` then `vercel deploy --prebuilt`.',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'vercel-mcp-release-safety-operator',
    name: 'Vercel MCP Release Safety',
    description:
      'Adds concise safety guidance for Vercel MCP deployment events, redeploy, domains, and environment variables.',
    category: 'deployment',
    metadataJson: {
      systemRole: 'vercel_mcp_release_operator',
      adminManaged: true,
      required: false,
      autoActivation: {
        enabled: true,
        triggers: ['vercel', 'deployment', 'env', 'domain'],
        toolNames: [...VERCEL_MCP_RELEASE_SAFETY_TOOLS],
      },
    },
    bodyMarkdown: [
      '# Skill Brief: Vercel MCP Release Safety',
      '',
      'Use this only when a Vercel MCP release, domain, deployment event, or environment variable tool is being called.',
      '',
      '## Applies To',
      `- ${formatCodeList(VERCEL_MCP_RELEASE_SAFETY_TOOLS)}`,
      '',
      '## Deployment Diagnosis',
      '- `vercel_create_deployment` only supports Git deployments in this wrapper. It does not upload the current workspace files.',
      '- Production deployments require explicit user intent for `target=production`.',
      '- Use deployment events before guessing why a build or deployment failed.',
      '- `vercel_redeploy_deployment` can only redeploy an existing deployment id. It is not a first source upload tool.',
      '- Do not treat `vercel_create_project_from_git` or `vercel_update_project_git_repository` as a completed deployment.',
      '- Do not replace a missing deployment-upload tool with ad hoc zip, tar, curl, or raw REST upload commands.',
      '',
      '## Environment Variables',
      '- Confirm the project and explicit target before writing or deleting env vars.',
      '- Do not guess `production`, `preview`, or `development`; use the user request or ask for clarification when the target is ambiguous.',
      '- Never expose secret values in the final answer or diagnostic logs. Report only key names, targets, and operation status.',
      '',
      '## Domains',
      '- Confirm the target project and domain ownership before adding a domain.',
      '- For production domains or routing-sensitive changes, ensure the user intent is explicit before calling the write tool.',
    ].join('\n'),
    resources: [
      {
        resourcePath: 'references/vercel-release-safety.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Vercel Release Safety Notes',
          '',
          '- Official MCP tools: https://vercel.com/docs/mcp/vercel-mcp/tools',
          '- Vercel recommends human confirmation for MCP tool execution and caution with prompt injection.',
          '- CLI source deployment docs: https://vercel.com/docs/cli/deploying-from-cli',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'ppt-workflow',
    name: 'PPT 工作流',
    description: '按竞品式子任务编排完成 PPT 生成前的需求分析、检索规划、素材简报、视觉方案、结构规划和渲染指令草稿',
    category: 'office',
    metadataJson: {
      systemRole: null,
      adminManaged: true,
      required: false,
      autoActivation: {
        enabled: true,
        triggers: ['ppt', 'pptx', 'powerpoint', 'presentation', 'slides', '演示文稿'],
        toolNames: [],
      },
    },
    bodyMarkdown: [
      '# Skill Brief: PPT 子任务编排工作流',
      '',
      '把当前任务当成 PPT 的“子任务编排 + 受控渲染”任务，而不是直接凭空生成 `.pptx`、HTML deck 或跳过规划。',
      '本 skill 复刻竞品截图中的前置工作流：需求分析、搜索规划、素材收集、视觉方案、结构规划、PPT 指令草稿和预检；当用户明确要求最终 PPTX 且预检通过后，再调用受控渲染器。',
      '',
      '## Activation Core',
      '- 适用场景：用户要求生成、规划、制作、改写或准备 PPT / PowerPoint / slides / 演示文稿。',
      '- 当前阶段不使用多子 agent；必须由单个 agent 按顺序执行多个子任务。',
      '- 不要在形成 `PptRenderInstructionDraft` 和 `PptPreflightReview` 前调用 PPT 专用渲染器。',
      '- 如果用户明确要求最终 PPTX，预检通过后调用 `render_pptx_from_instructions`，并把返回的 `.pptx` 路径放入 `complete_task.attachments`。',
      '- `ppt-workflow` active 时禁止自行写 `python-pptx`、PPTX 脚本或其他绕过渲染器的生成代码。',
      '- 必须先形成 `PptTaskAnalysis`，再决定是否需要检索；不要直接写逐页内容。',
      '- 如需搜索，必须先形成 `PptResearchPlan`；没有 research plan 时不要自由扩搜。',
      '- 不能只把同一套模板换颜色。每页必须根据内容选择 `layoutFamily`，且整份 deck 至少使用 4 种不同布局家族。',
      '- `title`、`coreMessage`、`contentBlocks` 不能互相复读；如果 `coreMessage` 已表达标题含义，正文必须提供新事实、例子、解释或证据。',
      '- 正文页内容必须有信息厚度：每页至少 2 个非重复内容块，优先包含 `insight`、`evidence`、`example`、`detail`、`source-note` 中的 2 类。',
      '- 结构型页面必须完整：`before-after` 必须左右两侧都有内容，`image-grid` 必须有图片或足够内容卡片，`timeline` 每个节点不能是长段落。',
      '- 节庆、民俗、传统文化主题必须使用更贴合题材的 festive / heritage 视觉方向，避免默认商务深绿模板。',
      '- 在正式输出前，必须形成 `PptRenderInstructionDraft` 和 `PptPreflightReview`。',
      '- 如果用户只给了主题且缺少关键约束，可以先问 1 到 3 个关键问题；如果有合理默认值，则继续推进并写清默认假设。',
      '',
      '## Fixed Subtask Order',
      '1. `ppt_intent_analyzer` -> `PptTaskAnalysis`',
      '2. `ppt_research_planner` -> `PptResearchPlan`',
      '3. `ppt_material_collector` -> `PptMaterialBrief`',
      '4. `ppt_visual_planner` -> `PptVisualPlan`',
      '5. `ppt_outline_planner` -> `PptDeckOutline`',
      '6. `ppt_render_instruction_planner` -> `PptRenderInstructionDraft`',
      '7. `ppt_preflight_reviewer` -> `PptPreflightReview`',
      '',
      '## Output Contract',
      '- 如果未进入渲染，最终回答必须按阶段汇总工作结果，明确哪些内容已准备好交给后续 PPT 渲染器。',
      '- 如果进入渲染，最终回答必须说明 PPTX 文件、页数、warning 和已完成验证。',
      '- 允许写入过程文件，例如 `ppt-workflow/task-analysis.json`、`ppt-workflow/research-plan.json`、`ppt-workflow/render-instructions.json`，但不要伪装为最终 PPT。',
      '- 若调用外部资料，必须保留来源 URL，并在 `PptMaterialBrief.sources` 或最终说明中列出。',
      '- 若存在素材缺口，必须明确标记缺口和建议补充方式。',
      '',
      '## Required Resources',
      '- 子任务契约：`references/subtask-contracts.md`',
      '- 视觉规划规范：`references/visual-plan-guide.md`',
      '- 审美风格规范：`references/aesthetic-style-guide.md`',
      '- 渲染指令草稿结构：`templates/render-instruction-draft.md`',
      '- 预检清单：`references/preflight-checklist.md`',
    ].join('\n'),
    resources: [
      {
        resourcePath: 'references/subtask-contracts.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# PPT Workflow Subtask Contracts',
          '',
          '## PptTaskAnalysis',
          '',
          '字段：',
          '- `rawRequest`',
          '- `topic`',
          '- `audience`',
          '- `purpose`',
          '- `lengthHint`',
          '- `coreAmbiguities`',
          '- `informationGaps`',
          '- `requiresSearch`',
          '- `assumptions`',
          '',
          '## PptResearchPlan',
          '',
          '字段：',
          '- `queries[]`',
          '- `coverageAreas[]`',
          '- `imageNeeds[]`',
          '- `excludedScope[]`',
          '- `expectedEvidenceTypes[]`',
          '',
          '## PptMaterialBrief',
          '',
          '字段：',
          '- `factHighlights[]`',
          '- `caseHighlights[]`',
          '- `candidateVisuals[]`，每项至少包含 `url`、`alt`、`sourceUrl`、`usageHint`，可直接进入 `imageSlots`。',
          '- `candidateVisuals[]` 数量要服务整份 deck：6 页以内至少 4 张不同图片，7 到 12 页至少 8 张不同图片；不足时写入 `materialGaps[]`，不要反复复用同一张图。',
          '- `logoOrBrandAssets[]`，只收集官方或可信来源 URL。',
          '- `conceptDiagramNeeds[]`',
          '- `sources[]`',
          '- `materialGaps[]`',
          '',
          '## PptDeckOutline',
          '',
          '字段：',
          '- `slideCount`',
          '- `sections[]`',
          '- `slides[]`，每页包含 `index`、`pageType`、`title`、`coreMessage`、`materialNeed`、`layoutIntent`、`visualRole`、`layoutFamily`。',
        ].join('\n'),
      },
      {
        resourcePath: 'references/visual-plan-guide.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# PPT Visual Plan Guide',
          '',
          '`PptVisualPlan` 至少包含：',
          '',
          '- `styleKeywords`：3 到 5 个风格词，例如现代、简洁、科技、专业。',
          '- `aestheticPreset`：只能从 `ink-classic`、`indigo-porcelain`、`forest-ink`、`kraft-paper`、`dune` 中选 1 个。AI / 技术 / 产品发布默认用 `indigo-porcelain`，通用商业默认用 `ink-classic`。',
          '- `canvas`：默认 `16:9`，可记录像素建议如 `960 x 540`，但不要把它当作唯一尺寸。',
          '- `fontSystem`：中文、英文/数字、代码或元数据字体角色。',
          '- `typeScale`：封面标题、页面标题、正文、注释和页脚层级。',
          '- `colorTokens`：背景、主色、辅助色、文本色和风险色。',
          '- `gridAndSpacing`：页边距、列网格、内容密度规则。',
          '- `rhythmPlan[]`：逐页列出 `index`、`visualRole`、`layoutFamily`。`visualRole` 只能是 `hero-dark`、`hero-light`、`light`、`dark`。',
          '- `coverDirection`、`dividerDirection`、`closingDirection`。',
          '',
          '硬规则：',
          '- 视觉方案必须服务主题和受众，不要只给泛泛的“科技感”。',
          '- 不要把整份 deck 规划成连续标题加项目符号。',
          '- 至少规划 3 种不同页面结构。',
          '- 采用“电子杂志 × 电子墨水”的审美约束，但不要生成 HTML deck：一份 deck 只选一套主题预设，标题/quote/大数字用衬线，正文用非衬线，元数据用等宽。',
          '- 必须先写主题节奏表：每页标明 `hero-dark`、`hero-light`、`light` 或 `dark`。连续 3 页以上同视觉角色不合格；8 页以上必须至少有 1 页 `hero-dark` 和 1 页 `hero-light`。',
          '- 图片是第一公民：优先收集/生成能嵌入 PPT 的主视觉、截图、信息图或图文面板素材；图片框使用标准比例，顶部和左右不可裁切。',
          '- 布局从固定家族中选，不要自由发挥成白底标题正文：`hero-cover`、`act-divider`、`big-number`、`quote-image`、`image-grid`、`pipeline`、`question`、`big-quote`、`before-after`、`lead-image-side-text`。',
          '- 同一份 deck 不要只用 `lead-image-side-text`；按内容混用数据、流程、对比、引用、图网格和图文页。',
          '- `coreMessage` 是标题下的观点句，不是标题的改写；正文内容块必须向下展开，不要复制 `coreMessage`。',
        ].join('\n'),
      },
      {
        resourcePath: 'references/aesthetic-style-guide.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# PPT Aesthetic Style Guide',
          '',
          '本指南吸收 `op7418/guizang-ppt-skill` 的审美方法，但本系统仍生成 PPTX，不生成 HTML deck。',
          '',
          '## 主题预设',
          '',
          '- `ink-classic`：墨黑 + 暖纸白，适合通用商业、思想分享。',
          '- `indigo-porcelain`：深靛蓝 + 瓷白，适合 AI、技术、产品发布、研究和数据。',
          '- `forest-ink`：森林绿 + 象牙，适合可持续、文化、行业观察。',
          '- `kraft-paper`：深棕 + 牛皮纸，适合人文、历史、阅读、怀旧。',
          '- `dune`：炭灰 + 沙色，适合设计、艺术、品牌和审美优先场景。',
          '',
          '规则：一份 deck 只能选一套主题预设，不要混搭颜色，不要让模型随意发明 hex 色板。',
          '',
          '## 字体分工',
          '',
          '- 大标题、章节标题、quote、数据大字：衬线字体。',
          '- 正文、说明、步骤、列表：非衬线字体。',
          '- 页眉、页码、来源、标签、版本号：等宽字体。',
          '',
          '## 视觉节奏',
          '',
          '- 每页必须标 `visualRole`：`hero-dark`、`hero-light`、`light`、`dark`。',
          '- 开场优先 `hero-dark`；章节页在 `hero-dark` 和 `hero-light` 间交替。',
          '- 不允许连续 3 页以上相同视觉角色。',
          '- 8 页以上必须至少包含 1 页 `hero-dark` 和 1 页 `hero-light`。',
          '- 正文页也需要穿插 `dark`，避免整份 deck 白底堆叠。',
          '',
          '## 布局家族',
          '',
          '- `hero-cover`：封面，大标题 + 副标题 + 元数据 + 主视觉。',
          '- `act-divider`：章节幕封，短标题 + 留白 + 强节奏。',
          '- `big-number`：数据大字报，少量指标强展示。',
          '- `quote-image`：左文右图，故事、反差、人物或场景。',
          '- `image-grid`：多图对比、截图证据。',
          '- `pipeline`：步骤、流程、方法论。',
          '- `question`：悬念问题或收束页。',
          '- `big-quote`：一句话 takeaway。',
          '- `before-after`：旧模式 vs 新模式。',
          '- `lead-image-side-text`：主文本 + 辅助图的密集信息页。',
          '',
          '## 图片规则',
          '',
          '- 图片是内容，不是装饰；优先选择能证明观点的截图、产品图、图表、人物或场景。',
          '- 图片框使用标准比例：16:9、16:10、4:3、3:2、1:1、3:4。',
          '- 顶部和左右不要裁切，必要时只裁底部。',
          '- 图片不要自带 PPT 标题、页脚、页码、角标或厚装饰边。',
          '- 图片不加厚边框和强阴影，最多使用轻微圆角和极淡分隔。',
          '',
          '## 内容厚度',
          '',
          '- 普通正文页至少 2 到 4 个内容块，每个内容块承担不同角色：观点、解释、例子、证据、行动建议或来源。',
          '- 禁止 `title`、`coreMessage`、第一个 paragraph 三者写成同一句话。',
          '- 同一主题下的分页面要拆出不同角度，例如背景、人物、场景、流程、价值、争议、案例、结论，而不是重复总述。',
          '- 如果材料不足，回到 `ppt_material_collector` 补资料，不要用空泛句子撑版面。',
        ].join('\n'),
      },
      {
        resourcePath: 'templates/render-instruction-draft.md',
        resourceType: 'template',
        contentMarkdown: [
          '# PptRenderInstructionDraft Template',
          '',
          '```json',
          '{',
          '  "deck": {',
          '    "title": "",',
          '    "audience": "",',
          '    "purpose": "",',
          '    "slideCount": 0,',
          '    "status": "pre_render_draft"',
          '  },',
          '  "theme": {',
          '    "styleKeywords": [],',
          '    "canvas": "",',
          '    "fontSystem": {},',
          '    "typeScale": {},',
          '    "colorTokens": {},',
          '    "gridAndSpacing": {},',
          '    "aestheticPreset": "ink-classic | indigo-porcelain | forest-ink | kraft-paper | dune",',
          '    "rhythmPlan": [',
          '      { "index": 1, "visualRole": "hero-dark", "layoutFamily": "hero-cover" }',
          '    ],',
          '    "qualityRules": [',
          '      "serif titles, sans body, mono metadata",',
          '      "hero and non-hero pages alternate",',
          '      "images use standard frames and preserve top/left/right"',
          '    ]',
          '  },',
          '  "slides": [',
          '    {',
          '      "index": 1,',
          '      "pageType": "cover",',
          '      "title": "",',
          '      "coreMessage": "",',
          '      "layoutIntent": "",',
          '      "visualRole": "hero-dark | hero-light | light | dark",',
          '      "layoutFamily": "hero-cover | act-divider | big-number | quote-image | image-grid | pipeline | question | big-quote | before-after | lead-image-side-text",',
          '      "kicker": "",',
          '      "chrome": { "left": "", "right": "" },',
          '      "contentBlocks": [],',
          '      "imageSlots": [',
          '        {',
          '          "url": "",',
          '          "alt": "",',
          '          "sourceUrl": "",',
          '          "usageHint": "cover | right-visual | diagram | logo"',
          '        }',
          '      ],',
          '      "sourceRefs": []',
          '    }',
          '  ],',
          '  "sources": [],',
          '  "openQuestions": []',
          '}',
          '```',
        ].join('\n'),
      },
      {
        resourcePath: 'references/preflight-checklist.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# PPT Workflow Preflight Checklist',
          '',
          '完成前检查：',
          '',
          '- 用户原始需求是否被覆盖。',
          '- 是否清楚说明默认假设。',
          '- 需要搜索时是否先有 `PptResearchPlan`。',
          '- 外部事实和素材是否保留来源 URL。',
          '- `PptDeckOutline` 是否有封面、主体和收束页。',
          '- 是否避免连续多页重复同一种结构。',
          '- 是否已读取 `references/aesthetic-style-guide.md` 并选择 `aestheticPreset`。',
          '- `theme.rhythmPlan` 是否覆盖每一页，且没有连续 3 页以上相同 `visualRole`。',
          '- 标题/quote/大数字、正文、元数据是否分别使用衬线、非衬线、等宽角色。',
          '- 图片是否进入 `imageSlots`，且没有把标题、页脚、页码、装饰边画进图片本身。',
          '- 是否至少使用 4 种 `layoutFamily`；是否避免连续 2 页同一布局。',
          '- 是否存在标题、核心句、正文首句重复；有重复则必须重写正文块。',
          '- 图片 URL 是否有足够差异；除 logo 外，同一张图片不要连续复用。',
          '- 是否存在空白结构槽、空白半栏、只有边框没有内容的页面；存在则禁止渲染。',
          '- `before-after` 是否左右都有内容；没有真实对照关系时改为 `lead-image-side-text` 或 `insight-cards`。',
          '- `image-grid` 是否至少有 1 张可用图片；图片不足时必须提供可转成内容卡片的 `contentBlocks`。',
          '- `timeline` / `pipeline` 节点是否短句化；长段落必须拆成 3 到 4 个纵向节点。',
          '- `PptRenderInstructionDraft` 是否可被后续渲染器消费。',
          '- 用户明确要求最终 PPTX 且预检通过时，下一步应调用 `render_pptx_from_instructions`。',
          '- 未调用渲染器时，必须明确当前不是最终 PPT 文件。',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'office-docx',
    name: 'Word 文档',
    description: '创建、改写或重组可直接交付的正式办公文档',
    category: 'office',
    bodyMarkdown: [
      '# Skill Brief: Word 办公文档生成与编辑',
      '',
      '请以专业办公文档作者、编辑和内容策略顾问的标准完成当前任务，并直接推进到可交付结果。',
      '',
      '## 总原则',
      '- 不要把 Word 任务当成“统一写一份报告”，而要按固定阶段协同推进。',
      `- 六个内部阶段必须按固定顺序执行：${formatCodeList(DOCX_PHASE_SKILLS)}。`,
      '- 先判定任务模式、文档原型和结构策略，再写正文和生成 `.docx`。',
      '',
      '## 交付要求',
      '- 最终产物优先生成可直接交付的 `.docx`。',
      '- 必须在最终 `.docx` 同目录写入 `document_manifest.json`，并记录 `artifactType`、`fileName`、`contentArchetype`、`stylePack`、`sectionCount`、`sourcePreservationRequired`。',
      '- `document_manifest.json.fileName` 必须等于最终 `.docx` 文件名；完成前必须用脚本或库打开 `.docx` 验证一次。',
      '- 如使用外部资料，必须保留来源 URL，可放在参考资料、附录、脚注式说明或验证说明中。',
      '- 当 `.docx` 已生成且完成一次结构或文件验证后，立即将其作为最终交付物完成。',
    ].join('\n'),
    resources: [
      {
        resourcePath: 'templates/formal-report-outline.md',
        resourceType: 'template',
        contentMarkdown: [
          '# Formal Report Outline',
          '',
          '1. 标题与摘要',
          '2. 背景与目标',
          '3. 现状分析',
          '4. 建议方案',
          '5. 实施步骤',
          '6. 风险与附录',
        ].join('\n'),
      },
    ],
  },
  {
    slug: 'office-xlsx',
    name: 'Excel 表格',
    description: '创建、分析、改写或校验可直接交付的工作簿与数据表',
    category: 'office',
    bodyMarkdown: [
      '# Skill Brief: Excel 表格生成、分析与编辑',
      '',
      '请以专业办公数据分析与工作簿设计者的标准完成当前任务，并直接推进到可交付结果。',
      '',
      '## 总原则',
      '- 不要把 Excel 任务当成“写一张表”，而要按固定阶段协同推进。',
      `- 六个内部阶段必须按固定顺序执行：${formatCodeList(XLSX_PHASE_SKILLS)}。`,
      '- 先判定任务模式、工作簿结构和公式策略，再生成 `.xlsx`。',
      '',
      '## 交付要求',
      '- 最终产物优先生成可直接交付的 `.xlsx`。',
      '- 必须在最终 `.xlsx` 同目录写入 `workbook_manifest.json`，并记录 `artifactType`、`fileName`、`contentArchetype`、`sheetCount`、`requiresFormulas`、`requiresSourceSheet`。',
      '- `workbook_manifest.json.fileName` 必须等于最终 `.xlsx` 文件名；完成前必须用脚本或库打开 workbook 验证一次。',
      '- 如使用外部数据，必须保留来源 URL、日期、单位和口径说明。',
      '- 当 `.xlsx` 已生成且完成一次文件或 workbook 结构验证后，立即将其作为最终交付物完成。',
    ].join('\n'),
    resources: [
      {
        resourcePath: 'references/workbook-qa-checklist.md',
        resourceType: 'reference',
        contentMarkdown: [
          '# Workbook QA Checklist',
          '',
          '- 至少区分输入区、计算区、输出区，避免所有内容堆在一张表。',
          '- 关键汇总值优先保留公式，不要只粘贴结果。',
          '- 当使用外部数据时，增加来源说明和更新时间。',
        ].join('\n'),
      },
    ],
  },
];
